flowchart TB
    subgraph " "
    v0["Channel.fromFilePairs"]
    v6[" "]
    end
    subgraph taxonomy_analysis_kraken
    subgraph TAXONOMY_ANALYSIS_COMPARE_KRAKEN
    v1([FQ1])
    v2([TRIM_ADAPT])
    v3([TRIM_4_NUCL])
    v4([KRAKEN2])
    v7([BRACKEN_EACH])
    end
    v11([MULTIQC])
    v8(( ))
    end
    subgraph " "
    v5[" "]
    v12[" "]
    end
    v0 --> v1
    v0 --> v2
    v1 --> v8
    v2 --> v3
    v3 --> v4
    v4 --> v7
    v4 --> v5
    v4 --> v8
    v6 --> v7
    v7 --> v8
    v8 --> v11
    v11 --> v12
